LOCAL_PATH:= $(call my-dir)

ifeq ($(TARGET_DEVICE),sero8)

include $(CLEAR_VARS)
LOCAL_SRC_FILES := rkcrc.c
LOCAL_STATIC_LIBRARIES := libmincrypt
LOCAL_MODULE := rkcrc
LOCAL_MODULE_TAGS := optional
include $(BUILD_HOST_EXECUTABLE)

include $(CLEAR_VARS)
LOCAL_SRC_FILES := rkcrc.c
LOCAL_STATIC_LIBRARIES := libmincrypt libcutils libc
LOCAL_MODULE := rkcrc
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM := rkcrc
LOCAL_MODULE_CLASS := UTILITY_EXECUTABLES
LOCAL_UNSTRIPPED_PATH := $(PRODUCT_OUT)/symbols/utilities
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/utilities
LOCAL_FORCE_STATIC_EXECUTABLE := true
include $(BUILD_EXECUTABLE)

endif
